language: node_js
branches:
  only:
  - src
node_js:
- "node"
cache: yarn
script:
- "yarn test"
- "yarn build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: "build"
  target_branch: master
  on:
    branch: src
    tags: true
